export const skillCategories = [
  {
    category: "Machine Learning & AI",
    items: [
      "Computer Vision (Object Detection, Object Tracking, YOLO)",
      "Reinforcement Learning (Continual RL, MARL)",
      "Deep Learning (Neural Networks)",
      "Natural Language Processing",
      "Tokenization",
      "Supervised Learning (Regression, Classification)",
      "Machine Learning Algorithms",
      "ML Lifecycle (Data Processing, Feature Engineering, Hyperparameter Tuning, Model Evaluation)",
      "Statistical Analysis",
      "Probability",
      "scikit-learn",
      "Pandas",
      "NumPy",
      "OpenCV",
      "Matplotlib",
    ],
  },
  {
    category: "Robotics",
    items: [
      "CAD (Computer-Aided Design)",
      "Mechanical Design",
      "PID Control",
      "Electrical Wiring & Soldering",
      "Kinematics",
      "Machining (Lathe, Mill)",
    ],
  },
  {
    category: "Programming Languages, Web & Databases",
    items: [
      "Python",
      "C++",
      "Java",
      "C",
      "JavaScript",
      "HTML",
      "CSS",
      "SQL",
      "MongoDB",
    ],
  },
  {
    category: "Software Engineering",
    items: [
      "Algorithms",
      "Data Structures",
      "API Development (REST, Postman)",
      "Full-Stack Development",
      "Object-Oriented Design",
      "Debugging",
      "Testing",
      "Node.js",
      "Git",
      "AWS EC2",
    ],
  },
  {
    category: "Systems & Low-Level",
    items: [
      "Embedded Systems",
      "Bare-Metal Programming",
      "Interrupts",
      "Event-Driven Systems",
      "Computer Architecture",
      "Distributed Systems",
      "IoT",
      "RF Protocols",
      "Serial Communication (SPI, I2C, UART)",
    ],
  },
];
